project:
  type: book
  output-dir: docs

book:
  title: "EC338 Pre-reading"
  author: "Neil Lloyd"
  date: "2023-10-03"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Test Part"
      chapters:
      - linear-reg.qmd
      - ols.qmd
      - geometry-ols.qmd
      - dummy-var.qmd
      - compendium.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

